"""staleness, manual import, comment edits

Revision ID: 25539a421708
Revises: 9e8c5a8f3e22
Create Date: 2026-09-30 16:13:32.153274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25539a421708'
down_revision: Union[str, Sequence[str], None] = '9e8c5a8f3e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_sources', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('candidate_sources', sa.Column('gone_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_sources', sa.Column('imported_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('candidate_sources_imported_by_id_fkey', 'candidate_sources', 'users', ['imported_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidates', sa.Column('stale_since', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_candidates_stale_since'), 'candidates', ['stale_since'], unique=False)
    op.add_column('comments', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_states', sa.Column('last_complete_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_states', 'last_complete_at')
    op.drop_column('comments', 'edited_at')
    op.drop_index(op.f('ix_candidates_stale_since'), table_name='candidates')
    op.drop_column('candidates', 'stale_since')
    op.drop_constraint('candidate_sources_imported_by_id_fkey', 'candidate_sources', type_='foreignkey')
    op.drop_column('candidate_sources', 'imported_by_id')
    op.drop_column('candidate_sources', 'gone_at')
    op.drop_column('candidate_sources', 'last_seen_at')
    # ### end Alembic commands ###
