"""candidate matching keys

Revision ID: 9e8c5a8f3e22
Revises: 8bee0446e54e
Create Date: 2026-09-30 15:52:02.818472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8c5a8f3e22'
down_revision: Union[str, Sequence[str], None] = '8bee0446e54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_sources', sa.Column('owner_id', sa.String(length=128), nullable=True))
    op.create_index('ix_candidate_sources_source_owner_id', 'candidate_sources', ['source', 'owner_id'], unique=False)
    op.add_column('candidates', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_candidates_birth_date'), 'candidates', ['birth_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_birth_date'), table_name='candidates')
    op.drop_column('candidates', 'birth_date')
    op.drop_index('ix_candidate_sources_source_owner_id', table_name='candidate_sources')
    op.drop_column('candidate_sources', 'owner_id')
    # ### end Alembic commands ###
